### ISSUE TITLE
DevOps metrics for current teams and system

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#100]
As a system owner, I would like to obtain current DevOps metrics for my system so that I can assess what needs improvement.

DevOps metrics:
* Frequency of deployment - how often does each team deploy to production
* Lead time for changes - how long does it take from merge of change to get change into production
* Change failure rate - percentage of code change that require fixes after deployment to production
* Time to restore services - how long does it take to bring system up from a service interruption or failure

AC:
* [ ] DevOps metrics from each app team is obtained
* [ ] DevOps metrics from infra team is obtained
* [ ] Metrics are published to a document accessible by system owner

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
