### ISSUE TITLE
Evaluate OSSEC status

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#132]
During controls documentation, we provided a response of OSSEC for certain controls. However, it's not confirmed that OSSEC is actually running.

IDS-Logs machine is likely host. SSH into the machine, see whether we find evidence of OSSEC running, if so, how it's configured and how to access the UI.

Pairing Encouraged. Here's more info about [OSSEC](https://www.ossec.net/docs/)

See [CA-07](https://box.com/integrations/googledss/openGoogleEditor?fileId=823299204369&trackingId=3#gid=595525770&range=39:39)

AC:
* [x] Results of OSSEC evaluation is documented in this ticket
* [x] New tickets are generated for next steps if any
* [x] Controls spreadsheet is updated to reflect current status

**Comment by kilbergr** [comment]
Confirmed if you ssh into ids-logs, cd into /var/ dir, there's an ossec dir.

**Comment by kilbergr** [comment]
```
Get on VPN
SSH into ids-logs
sudo su root
cd var/ossec
```

**Comment by kilbergr** [comment]
```
[root@logs ossec]# bin/ossec-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
```

**Comment by kilbergr** [comment]
OSSec is only running on Tomcat1 and 2, Lifeboat, and MobileApp-Locator, and IDS-Logs servers. I believe they may be pushing to IDS-Logs.
Kibana is on IDS-Logs, but not running. You can start it by running `sudo service kibana start` and then visiting 10.2.1.5:5601 (5601 is the Kibana port). There it says "Kibana server is not ready yet". That's because it's trying to start up but it relies on a healthy elasticsearch instance and elasticsearch is down. When you run `curl http://localhost:9200/_cluster/health/?level=shards` from the IDS-Logs machine, you get this error:

```
"cluster_name":"elasticsearch","status":"red","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":327,"active_shards":327,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":672,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":32.732732732732735,[...]
```
Therefore, although it's true that OSSec is installed in a few places, it is not true to claim that "ECLKC servers are currently protected via firewall with an Intrusion Prevention System in place.", because OSSec is not implemented as described.
