### ISSUE TITLE
[POAM] Software inventory

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#141]
We need to include software tools used by hosting and app teams in our asset inventory and track any applicable licenses as required by our configuration management controls.

See CM-10 in [Controls spreadsheet](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7)

AC:

- [ ] List of software tools added to [Asset_Inventory.xlsx](https://acf-headstart.box.com/s/t3ahwlw9gu2yawhaf7mxn7jxru0o5ass) spreadsheet
- [ ] List includes license type and license term and expiration if applicable
- [ ] List includes team using it
- [ ] Internally reviewed

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
