### ISSUE TITLE
System monitoring and notifications

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#151]
As a hosting team member, I need to be aware of critical infrastructure issues affecting the system as soon as they happen so that I can address them quickly to minimize impact to our users and maintain our required 99% up time.

Background:
Currently, the hosting team does not have any monitoring of the system at all. We are dependent on the application teams letting us know of all issues. However, the application teams also don't have any monitoring of the system so they depend on ad hoc checks and complaints from users and other stakeholders. This leads to issues not being noticed quickly and users being impacted for longer than they should.
The hosting team would be able to respond quicker if they were able to detect and be notified of issues sooner.

Outcomes:
* Critical infrastructure in the system is monitored for anomalies or issues
* Monitors notify hosting team automatically of issues so that they can take action and resolve as needed

Details:
* What needs to be monitored in AWS so that can maintain 99% uptime?
   * All websites and load balancers and Route53
* Where should we send notifications once monitors are set up?
   * SMS to full team
* What should threshold to alert team members be vs. just being logged?
  * Can be determined during implementation

AC:

- [x] Monitoring systems set up to detect infrastructure issues that can affect site availability and functionality
- [x] Alerts are configured for monitors so that hosting team is notified automatically once issues are detected
- [x] Monitoring and alert configuration is documented

**Comment by kilbergr** [comment]
Tickets 83-87 to address the work spelled out in these design docs.

**Comment by ssatagopan** [comment]
Design docs along with related new tickets will achieve desired outcome
