### ISSUE TITLE
Create implementation plan for migration of MariaDB from EC2 to RDS

### ISSUE THREAD

**Issue by kilbergr** [OHS-Hosting-Infrastructure/infrastructure#163]
Using the outcome from https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/25 ADR to guide your implementation suggestions, write step by step what it will take to complete the migration plan.

Linked to https://github.com/OHS-Hosting-Infrastructure/environment-configuration/issues/72 (do that one and describe steps in this one)

Note, we can make the configuration changes during a maintenance window to make the migration easier.

Include how to terraform the resources.
Include a plan for testing this on staging with the help from dev teams.

Open questions
- What are the configuration changes we need to make in production to support this?
- How does this affect the sync to west/lifeboat?
- How do the different applications access the database?

Outcome:
- [ ] Tickets created to migrate to a better management experience for MariaDB. 

AC:
- [ ] an extensive migration plan from EC2 to RDS
- [ ] NUMBERED issues that represent ORDERED tasks for this migration

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
