### ISSUE TITLE
Create run book for some common maintenance tasks

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#192]
We need some run books for some common tasks so that team knows what to do and it is documented.

AC:
- [ ] Run book for increasing disk space on any Linux machine
- [ ] Run book for updating packages on Ubuntu and Centos
- [ ] Run book for updating package like NodeJS that requires upstream repo update

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
