### ISSUE TITLE
[User Research] User Interview Plan

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#198]
As part of our user research plan, we need to conduct individual user interviews so that we can identify needs and pain points from different stakeholders' perspective.

AC:
- [ ] User Interview Plan documented
- [ ] Plan includes identified stakeholders to interview
- [ ] Plan includes interview questions per identified stakeholder or type of stakeholder

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
