### ISSUE TITLE
[Technical Research] SSH access policy and tech

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#21]
What are the levels of access we want to give to devs, hosting team members etc?
Individual user should have individual users and ssh access to each machine. How should we provision said access and keep these things up to date?

Outcomes:
- [ ] the hosting team can provision access to themselves and dev teams for appropriate resources
- [ ] the hosting team has a plan to implement ssh access in a more secure auditable manner

AC:
- [ ] ADR describing the decision for how we should manage ssh user access to machines and an implementation plan
- [ ] New work in the backlog for creating ssh access

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
