### ISSUE TITLE
[Technical Research] Plan for migration off mail server

### ISSUE THREAD

**Issue by eeeady** [OHS-Hosting-Infrastructure/infrastructure#22]
We have a mail server. We don't want to manage said mail server.

Evaluate the level of effort and plan to migrate off the mail server.
General draft of steps required:
- determine the domains and mailing lists for those domains configured on the mail server.
- determine what the dev teams are currently using the mail server for (sending/receiving)
- determine how we can manage ses configuration in terraform
- write a plan for migration of mail services off of mail.eclkc.info
- gotchas?

Outcomes:
- [ ] The hosting team knows how hard it will be to migrate off of the existing mail server

AC:
- [ ] A document outlining the proposed migration steps
- [ ] A set of issues/work for us to complete on the planning board

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
