### ISSUE TITLE
[ATO] System Architecture

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#75]
System Architecture is a component of several ATO documents and would be helpful if this is documented to be referenced in ATO documents.

This includes both a diagram with ATO boundary and text description of architecture, including technology components of the system, hardware and software.

- [ ] System Architecture document available to be referenced by ATO documents
- [ ] System Architecture document contains diagram with components along with ATO boundary demarcation
- [ ] System Architecture document contains description of architecture, including functional and technical components
- [ ] System Architecture document describes data flow

**Comment by eeeady** [comment]
Got the visio template and started looking into it.
