### ISSUE TITLE
[ATO] Security Controls documentation (Security Assessment and Authorization)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#80]
Need to complete Security Assessment and Authorization section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

AC:
- [ ] Security Assessment and Authorization section of Security Controls filled out
- [ ] Reviewed internally

**Comment by jduss4** [comment]
CA-01 has implementation comment that has not been added to description yet

CA-02 we need more information from OHS about the ECLKC security assessment plan

CA-07 need to investigate if OSSEC is operating

CA-09 could add information about infrastructure as code for documentation

**Comment by ssatagopan** [comment]
* [x] CA-01 - copied over text from comment to implementation description
* [ ] CA-02 - need answer from ISSO
* [x] CA-07 - created https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-65061474
* [x] CA-09 - no changes needed for current ATO, but will include as part of keeping ATO documentation up to date
