### ISSUE TITLE
[ATO] Security Controls documentation (Contingency Planning)

### ISSUE THREAD

**Issue by ssatagopan** [OHS-Hosting-Infrastructure/infrastructure#82]
Need to complete Contingency Planning section of [Security Controls ](https://acf-headstart.box.com/s/dzrw2lcs1gzrtxli5ngteq5vmvtealr7) document.

[Previous ATO Controls](https://acf-headstart.box.com/s/dkzxy3ojktuy00pwf7pv6clsjgruphec)

BLOCKED by:
https://github.com/orgs/OHS-Hosting-Infrastructure/projects/1#card-63180554

AC:
[ ] Contingency Planning section of Security Controls filled out
[ ] Reviewed internally and submitted to ISSO

**Comment by jduss4** [comment]
CP-02 need to write contingency plan :)
CP-03 schedule contingency operations exercise for September 2021
CP-04 find most recent contingency plan and test results

**Comment by jduss4** [comment]
I think the most recent contingency plan was September 2020 (see Box "SOP COOP Exercise.docx" ) and it has a link to documentation of a test run

**Comment by ssatagopan** [comment]
* [x]CP-02 Can leave content as is with implicit understanding that Contingency Plan is part of ATO material anyway
* [x] CP-03 Created https://github.com/OHS-Hosting-Infrastructure/infrastructure/issues/133 for exercise
* [x] CP-04 [Last run](https://acf-headstart.box.com/s/yshxklvmqrmweeaasivilmzivz9a2z98) and [COOP Plan](https://acf-headstart.box.com/s/mjo6lrzyfww80buvjjyjtbsqwie3i99l)
